Batch update
gtalarico/airtable-python-wrapper pull request #107
Opened 2020-10-23 13:17 UTC by thomasopsomer

As the title says, just a simple method to update records in batch :)

And line ending should be ok this time :)

2020-11-09 15:52 UTC, gtalarico requested changes
Looks great, thank you for the PR!
Just need `Arg` change on docstring

2020-11-09 15:52 UTC, gtalarico commented on airtable/airtable.py
> +            records(``dict``): List of dict: [{"id": record_id, "field": fields_to_update_dict}]
Could you add missing `Arg` documentation?
https://github.com/gtalarico/airtable-python-wrapper/blob/d829743342c34e11e1fb38fc5579a0533af4900a/airtable/airtable.py#L524

2021-02-12 10:19 UTC, thomasopsomer commented
Sorry I forgot about this... just fixed the docstring

2021-02-15 21:09 UTC, gtalarico approved these changes
LG, thanks!
We should probably include "Default is `False" in doc string but we can fix this in sep. PR

2021-02-15 21:09 UTC, merged

2021-03-13 16:58 UTC, DylanScotney commented
Hey @gtalarico do you plan on doing a new release to include this? Would be great to have it as part of the pypi library!

2021-03-13 22:10 UTC, gtalarico commented
Thanks for the bump @DylanScotney 
released as .15.12
https://pypi.org/project/airtable-python-wrapper/#history